### ISSUE TITLE
cargo-miri does not support workspaces

### ISSUE THREAD

**Issue by jamii** [rust-lang/miri#1001]
```
[nix-shell:~/materialize]$ RUST_BACKTRACE=full cargo miri test
thread 'main' panicked at 'could not find matching package', src/libcore/option.rs:1186:5
stack backtrace:
   0:     0x5651a7ff78b4 - backtrace::backtrace::libunwind::trace::h187f113b2abb647f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x5651a7ff78b4 - backtrace::backtrace::trace_unsynchronized::h38320d8128cd24b5
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x5651a7ff78b4 - std::sys_common::backtrace::_print_fmt::h556c1c2dcb1a6658
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x5651a7ff78b4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc8b96dbda96cbdc1
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x5651a801a64c - core::fmt::write::h5df803e3899d44e6
                               at src/libcore/fmt/mod.rs:1028
   5:     0x5651a7ff4377 - std::io::Write::write_fmt::h68c8001b57139b09
                               at src/libstd/io/mod.rs:1412
   6:     0x5651a7ff9d5e - std::sys_common::backtrace::_print::hd5e7e75fe3073c40
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x5651a7ff9d5e - std::sys_common::backtrace::print::he7bb8f2987194f75
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x5651a7ff9d5e - std::panicking::default_hook::{{closure}}::hb1d0eb5b0ef71aca
                               at src/libstd/panicking.rs:189
   9:     0x5651a7ff9a61 - std::panicking::default_hook::h180de3c633f62ee7
                               at src/libstd/panicking.rs:206
  10:     0x5651a7ffa3a5 - std::panicking::rust_panic_with_hook::hdbd08e13a7c982fe
                               at src/libstd/panicking.rs:469
  11:     0x5651a7ff9f42 - std::panicking::continue_panic_fmt::hce8732bd3590e67f
                               at src/libstd/panicking.rs:376
  12:     0x5651a7ff9e36 - rust_begin_unwind
                               at src/libstd/panicking.rs:303
  13:     0x5651a80174da - core::panicking::panic_fmt::h6ae4e581ed6dc186
                               at src/libcore/panicking.rs:84
  14:     0x5651a8017547 - core::option::expect_failed::he6206254f2567eda
                               at src/libcore/option.rs:1186
  15:     0x5651a7fb31e3 - cargo_miri::in_cargo_miri::hcec20312bf94bc59
  16:     0x5651a7faffdc - cargo_miri::main::h27ebf5efc0e679f2
  17:     0x5651a7fb9a63 - std::rt::lang_start::{{closure}}::h86b770088dbcc250
  18:     0x5651a7ff9e23 - std::rt::lang_start_internal::{{closure}}::h7b205f4a42ad477c
                               at src/libstd/rt.rs:48
  19:     0x5651a7ff9e23 - std::panicking::try::do_call::h86e27d03bcc6125d
                               at src/libstd/panicking.rs:288
  20:     0x5651a8000a3a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  21:     0x5651a7ffa89d - std::panicking::try::hfc76a5c7339ca0f6
                               at src/libstd/panicking.rs:267
  22:     0x5651a7ffa89d - std::panic::catch_unwind::h49899aa9a0080a0f
                               at src/libstd/panic.rs:396
  23:     0x5651a7ffa89d - std::rt::lang_start_internal::hf860c9ff06c64238
                               at src/libstd/rt.rs:47
  24:     0x5651a7fb40d2 - main
  25:     0x7f2ceba08b8e - __libc_start_main
  26:     0x5651a7fabfb9 - <unknown>

[nix-shell:~/materialize]$ cargo miri -V
miri 0.1.0 (2adc39f 2019-10-14)

[nix-shell:~/materialize]$ xargo --version
xargo 0.3.16
cargo 1.40.0-nightly (a429e8cc4 2019-10-04)

[nix-shell:~/materialize]$ rustup show active-toolchain 
nightly-x86_64-unknown-linux-gnu (overridden by '/home/jamie/materialize/rust-toolchain')
```

Possibly relevant - this project is a cargo workspace which has caused problems for some other tools.

**Comment by jamii** [comment]
```
jamie@machine:~/materialize$ rustc --version
rustc 1.40.0-nightly (237d54ff6 2019-10-15)
```

**Comment by jamii** [comment]
Running inside individual crates does seem to work, so very likely a workspace issue.

**Comment by RalfJung** [comment]
Yeah I don't think we currently support workspaces. Does `cargo test`? Looking at https://github.com/rust-random/rand/blob/9221d93f7bcbb68bf886760d710ba269bb8b31b9/utils/ci/script.sh, they need to run the tests separately for each package in the workspace as well.

**Comment by jamii** [comment]
> Yeah I don't think we currently support workspaces

Fair enough. If I had realized it was a workspace issue right away I probably wouldn't have filed an issue.

> Does cargo test?

`cargo test` and `cargo bench` work. `rls` started working recently.

**Comment by RalfJung** [comment]
> Fair enough. If I had realized it was a workspace issue right away I probably wouldn't have filed an issue.

It is certainly a bug to panic here, so thanks for filing!

But beyond that, we'd certainly like to support workspace. `cargo miri test` should run the same code as `cargo test`. But really someone should re-write most of that cargo-miri wrapper as it is a bad mess. And I am unlikely to do it anytime soon, so this is a great opportunity to contribute. :)

> cargo test and cargo bench work.

And what do they do? Run the tests of all crates in the workspace?

**Comment by jamii** [comment]
Yep.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/miri/pull/1002 should fix the awful error message.

But let's keep this issue open to track workspace support.
