### ISSUE TITLE
ICE when `-Zmiri-track-alloc-id=6` in empty project

### ISSUE THREAD

**Issue by y86-dev** [rust-lang/miri#2076]
`cargo new ice_on_track_alloc && cd ice_on_track_alloc`
and then
`MIRIFLAGS="-Zmiri-track-alloc-id=6" cargo miri run`

Produces the following ICE:

<details><summary>ICE Stacktrace</summary>

```text
thread 'rustc' panicked at 'assertion failed: diagnostics.borrow().is_empty()', src/tools/miri/src/diagnostics.rs:344:40
stack backtrace:
   0:     0x7f4437da385d - std::backtrace_rs::backtrace::libunwind::trace::hd79e9b51bb0b02a3
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f4437da385d - std::backtrace_rs::backtrace::trace_unsynchronized::hc4b2624d11f57391
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4437da385d - std::sys_common::backtrace::_print_fmt::h5b920b6df28041d5
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f4437da385d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h01f2db48eea34166
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f4437dfeefc - core::fmt::write::h743b8fce003c331c
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/core/src/fmt/mod.rs:1194:17
   5:     0x7f4437d95041 - std::io::Write::write_fmt::h55edc38b905db9b5
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/io/mod.rs:1655:15
   6:     0x7f4437da6575 - std::sys_common::backtrace::_print::h72c54a6b7a86b7bf
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f4437da6575 - std::sys_common::backtrace::print::h8b541992f5fa33c9
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f4437da6575 - std::panicking::default_hook::{{closure}}::h47e8a61e5844dea4
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/panicking.rs:295:22
   9:     0x7f4437da61e9 - std::panicking::default_hook::h65ae1796882c178c
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/panicking.rs:314:9
  10:     0x7f44385445a1 - rustc_driver[caca827775d68846]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f4437da6d46 - std::panicking::rust_panic_with_hook::h1c3eee211b989bad
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/panicking.rs:702:17
  12:     0x7f4437da6b09 - std::panicking::begin_panic_handler::{{closure}}::h653627205f5b2cdc
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/panicking.rs:586:13
  13:     0x7f4437da3d14 - std::sys_common::backtrace::__rust_end_short_backtrace::h36d845a914b6aae7
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f4437da6879 - rust_begin_unwind
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/panicking.rs:584:5
  15:     0x7f4437d6bbd3 - core::panicking::panic_fmt::hb6389d787a80a806
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/core/src/panicking.rs:142:14
  16:     0x7f4437d6ba9d - core::panicking::panic::hac9e097b59d15ac2
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/core/src/panicking.rs:48:5
  17:     0x56499936be4b - <rustc_const_eval[ec16a9026af29337]::interpret::eval_context::InterpCx<miri[11bda64e92b8a89f]::machine::Evaluator> as miri[11bda64e92b8a89f]::diagnostics::EvalContextExt>::preprocess_diagnostics
  18:     0x5649992f7164 - miri[11bda64e92b8a89f]::eval::eval_entry
  19:     0x56499926a902 - <rustc_interface[dacacaf3651fe347]::passes::QueryContext>::enter::<<miri[aaa733ecb7479b45]::MiriCompilerCalls as rustc_driver[caca827775d68846]::Callbacks>::after_analysis::{closure#0}, ()>
  20:     0x56499926346e - <miri[aaa733ecb7479b45]::MiriCompilerCalls as rustc_driver[caca827775d68846]::Callbacks>::after_analysis
  21:     0x7f443a558ab5 - <rustc_interface[dacacaf3651fe347]::interface::Compiler>::enter::<rustc_driver[caca827775d68846]::run_compiler::{closure#1}::{closure#2}, core[864d7ae58f623181]::result::Result<core[864d7ae58f623181]::option::Option<rustc_interface[dacacaf3651fe347]::queries::Linker>, rustc_errors[14f27e81a88a2c7]::ErrorGuaranteed>>
  22:     0x7f443a5823ff - rustc_span[ff646084812721ee]::with_source_map::<core[864d7ae58f623181]::result::Result<(), rustc_errors[14f27e81a88a2c7]::ErrorGuaranteed>, rustc_interface[dacacaf3651fe347]::interface::create_compiler_and_run<core[864d7ae58f623181]::result::Result<(), rustc_errors[14f27e81a88a2c7]::ErrorGuaranteed>, rustc_driver[caca827775d68846]::run_compiler::{closure#1}>::{closure#1}>
  23:     0x7f443a56cd64 - rustc_interface[dacacaf3651fe347]::interface::create_compiler_and_run::<core[864d7ae58f623181]::result::Result<(), rustc_errors[14f27e81a88a2c7]::ErrorGuaranteed>, rustc_driver[caca827775d68846]::run_compiler::{closure#1}>
  24:     0x7f443a555fa1 - <scoped_tls[d6203f3b3010b98e]::ScopedKey<rustc_span[ff646084812721ee]::SessionGlobals>>::set::<rustc_interface[dacacaf3651fe347]::interface::run_compiler<core[864d7ae58f623181]::result::Result<(), rustc_errors[14f27e81a88a2c7]::ErrorGuaranteed>, rustc_driver[caca827775d68846]::run_compiler::{closure#1}>::{closure#0}, core[864d7ae58f623181]::result::Result<(), rustc_errors[14f27e81a88a2c7]::ErrorGuaranteed>>
  25:     0x7f443a56f54f - std[fd2a1eaf3e081d4d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[dacacaf3651fe347]::util::run_in_thread_pool_with_globals<rustc_interface[dacacaf3651fe347]::interface::run_compiler<core[864d7ae58f623181]::result::Result<(), rustc_errors[14f27e81a88a2c7]::ErrorGuaranteed>, rustc_driver[caca827775d68846]::run_compiler::{closure#1}>::{closure#0}, core[864d7ae58f623181]::result::Result<(), rustc_errors[14f27e81a88a2c7]::ErrorGuaranteed>>::{closure#0}, core[864d7ae58f623181]::result::Result<(), rustc_errors[14f27e81a88a2c7]::ErrorGuaranteed>>
  26:     0x7f443a56f689 - <<std[fd2a1eaf3e081d4d]::thread::Builder>::spawn_unchecked_<rustc_interface[dacacaf3651fe347]::util::run_in_thread_pool_with_globals<rustc_interface[dacacaf3651fe347]::interface::run_compiler<core[864d7ae58f623181]::result::Result<(), rustc_errors[14f27e81a88a2c7]::ErrorGuaranteed>, rustc_driver[caca827775d68846]::run_compiler::{closure#1}>::{closure#0}, core[864d7ae58f623181]::result::Result<(), rustc_errors[14f27e81a88a2c7]::ErrorGuaranteed>>::{closure#0}, core[864d7ae58f623181]::result::Result<(), rustc_errors[14f27e81a88a2c7]::ErrorGuaranteed>>::{closure#1} as core[864d7ae58f623181]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  27:     0x7f4437db0bf3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h211dae6d8dec3611
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/alloc/src/boxed.rs:1866:9
  28:     0x7f4437db0bf3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb54334e8a7bb1f12
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/alloc/src/boxed.rs:1866:9
  29:     0x7f4437db0bf3 - std::sys::unix::thread::Thread::new::thread_start::hf8b57655f2f2e68e
                               at /rustc/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/library/std/src/sys/unix/thread.rs:108:17
  30:     0x7f4437a6db1a - start_thread
  31:     0x7f4437af2660 - __GI___clone3
  32:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (4ca19e09d 2022-04-19) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental -Z miri-track-alloc-id=6

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```
</details>

**Comment by RalfJung** [comment]
Good catch!

If our setup phase that runs before any MIR is interpreted triggers diagnostics, then that is not handled properly.

**Comment by y86-dev** [comment]
Similar issue arises when using `-Zmiri-track-pointer-tag={i}` for `i in 1..13`:
<details>
<summary>
Stacktrace for i = 1
</summary>

```text
thread 'rustc' panicked at 'assertion failed: diagnostics.borrow().is_empty()', src/diagnostics.rs:344:40
stack backtrace:
   0:     0x7fb5eea4e87d - std::backtrace_rs::backtrace::libunwind::trace::hda12c320eecfcbca
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fb5eea4e87d - std::backtrace_rs::backtrace::trace_unsynchronized::hce155082c8690bcb
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb5eea4e87d - std::sys_common::backtrace::_print_fmt::h6d68d436c1ede92f
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fb5eea4e87d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8d171a2c298a02a1
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fb5eeaa9f1c - core::fmt::write::h723ba5814da9e1d4
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/core/src/fmt/mod.rs:1194:17
   5:     0x7fb5eea3ffc1 - std::io::Write::write_fmt::h288d785b1d0618f0
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/io/mod.rs:1655:15
   6:     0x7fb5eea51595 - std::sys_common::backtrace::_print::head26b2d7678237b
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fb5eea51595 - std::sys_common::backtrace::print::h4455a1b5eb6207ac
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fb5eea51595 - std::panicking::default_hook::{{closure}}::h41d76da6eb616d98
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/panicking.rs:295:22
   9:     0x7fb5eea51209 - std::panicking::default_hook::hb69e1ecf0cb80b69
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/panicking.rs:314:9
  10:     0x7fb5ef1eeed1 - rustc_driver[e289a4868ec6f5c3]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fb5eea51d66 - std::panicking::rust_panic_with_hook::h21741feec6704ad7
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/panicking.rs:702:17
  12:     0x7fb5eea51b29 - std::panicking::begin_panic_handler::{{closure}}::h50ca685700249376
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/panicking.rs:586:13
  13:     0x7fb5eea4ed34 - std::sys_common::backtrace::__rust_end_short_backtrace::h71643300a8e75965
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fb5eea51899 - rust_begin_unwind
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/panicking.rs:584:5
  15:     0x7fb5eea16bf3 - core::panicking::panic_fmt::hfe4b81e05f0858fd
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/core/src/panicking.rs:142:14
  16:     0x7fb5eea16abd - core::panicking::panic::h569d807c95e280ea
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/core/src/panicking.rs:48:5
  17:     0x55f28e638bea - miri::diagnostics::EvalContextExt::preprocess_diagnostics::{{closure}}::haf776f4ec2c2f08f
                               at ~/miri/src/diagnostics.rs:344:40
  18:     0x55f28e638bea - std::thread::local::LocalKey<T>::try_with::ha7cfc4e1b8671c6a
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/thread/local.rs:443:16
  19:     0x55f28e638bea - std::thread::local::LocalKey<T>::with::h3916ca3477e7d714
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/thread/local.rs:419:9
  20:     0x55f28e638bea - miri::diagnostics::EvalContextExt::preprocess_diagnostics::he472b1e4f6c7ee40
                               at ~/miri/src/diagnostics.rs:344:9
  21:     0x55f28e5d2c84 - miri::eval::eval_entry::{{closure}}::h2b63c94c681362b4
                               at ~/miri/src/eval.rs:310:24
  22:     0x55f28e5d2c84 - miri::eval::eval_entry::hb613585104d99bb9
                               at ~/miri/src/eval.rs:307:38
  23:     0x55f28e54da2e - <miri::MiriCompilerCalls as rustc_driver::Callbacks>::after_analysis::{{closure}}::h6ed2a93569f82ed4
                               at ~/miri/src/bin/miri.rs:82:40
  24:     0x55f28e54da2e - rustc_interface::passes::QueryContext::enter::{{closure}}::h4d63726f93808b9b
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/compiler/rustc_interface/src/passes.rs:819:42
  25:     0x55f28e54da2e - rustc_middle::ty::context::tls::enter_context::{{closure}}::h9c85a179706e33de
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/compiler/rustc_middle/src/ty/context.rs:1818:50
  26:     0x55f28e54da2e - rustc_middle::ty::context::tls::set_tlv::h829987acb8cfa2a2
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/compiler/rustc_middle/src/ty/context.rs:1802:9
  27:     0x55f28e54da2e - rustc_middle::ty::context::tls::enter_context::h92aeb683847d938c
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/compiler/rustc_middle/src/ty/context.rs:1818:9
  28:     0x55f28e54da2e - rustc_interface::passes::QueryContext::enter::h25131cc782623432
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/compiler/rustc_interface/src/passes.rs:819:9
  29:     0x55f28e547ac8 - <miri::MiriCompilerCalls as rustc_driver::Callbacks>::after_analysis::h5d6ae5ebc77665ad
                               at ~/miri/src/bin/miri.rs:59:9
  30:     0x7fb5f120afe5 - <rustc_interface[79a466e9fb7b31d]::interface::Compiler>::enter::<rustc_driver[e289a4868ec6f5c3]::run_compiler::{closure#1}::{closure#2}, core[a72dbdb3b588fbeb]::result::Result<core[a72dbdb3b588fbeb]::option::Option<rustc_interface[79a466e9fb7b31d]::queries::Linker>, rustc_errors[209cb86b9fab4aab]::ErrorGuaranteed>>
  31:     0x7fb5f123495f - rustc_span[d1744ebcfc1757dd]::with_source_map::<core[a72dbdb3b588fbeb]::result::Result<(), rustc_errors[209cb86b9fab4aab]::ErrorGuaranteed>, rustc_interface[79a466e9fb7b31d]::interface::create_compiler_and_run<core[a72dbdb3b588fbeb]::result::Result<(), rustc_errors[209cb86b9fab4aab]::ErrorGuaranteed>, rustc_driver[e289a4868ec6f5c3]::run_compiler::{closure#1}>::{closure#1}>
  32:     0x7fb5f120bc34 - rustc_interface[79a466e9fb7b31d]::interface::create_compiler_and_run::<core[a72dbdb3b588fbeb]::result::Result<(), rustc_errors[209cb86b9fab4aab]::ErrorGuaranteed>, rustc_driver[e289a4868ec6f5c3]::run_compiler::{closure#1}>
  33:     0x7fb5f1209c31 - <scoped_tls[e9ff1f48249a691c]::ScopedKey<rustc_span[d1744ebcfc1757dd]::SessionGlobals>>::set::<rustc_interface[79a466e9fb7b31d]::interface::run_compiler<core[a72dbdb3b588fbeb]::result::Result<(), rustc_errors[209cb86b9fab4aab]::ErrorGuaranteed>, rustc_driver[e289a4868ec6f5c3]::run_compiler::{closure#1}>::{closure#0}, core[a72dbdb3b588fbeb]::result::Result<(), rustc_errors[209cb86b9fab4aab]::ErrorGuaranteed>>
  34:     0x7fb5f1221a9f - std[c5de681ea323b56d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[79a466e9fb7b31d]::util::run_in_thread_pool_with_globals<rustc_interface[79a466e9fb7b31d]::interface::run_compiler<core[a72dbdb3b588fbeb]::result::Result<(), rustc_errors[209cb86b9fab4aab]::ErrorGuaranteed>, rustc_driver[e289a4868ec6f5c3]::run_compiler::{closure#1}>::{closure#0}, core[a72dbdb3b588fbeb]::result::Result<(), rustc_errors[209cb86b9fab4aab]::ErrorGuaranteed>>::{closure#0}, core[a72dbdb3b588fbeb]::result::Result<(), rustc_errors[209cb86b9fab4aab]::ErrorGuaranteed>>
  35:     0x7fb5f1221be9 - <<std[c5de681ea323b56d]::thread::Builder>::spawn_unchecked_<rustc_interface[79a466e9fb7b31d]::util::run_in_thread_pool_with_globals<rustc_interface[79a466e9fb7b31d]::interface::run_compiler<core[a72dbdb3b588fbeb]::result::Result<(), rustc_errors[209cb86b9fab4aab]::ErrorGuaranteed>, rustc_driver[e289a4868ec6f5c3]::run_compiler::{closure#1}>::{closure#0}, core[a72dbdb3b588fbeb]::result::Result<(), rustc_errors[209cb86b9fab4aab]::ErrorGuaranteed>>::{closure#0}, core[a72dbdb3b588fbeb]::result::Result<(), rustc_errors[209cb86b9fab4aab]::ErrorGuaranteed>>::{closure#1} as core[a72dbdb3b588fbeb]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  36:     0x7fb5eea5bc13 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9b3211b77ff3a85d
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/alloc/src/boxed.rs:1866:9
  37:     0x7fb5eea5bc13 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h903e1e2332b0ad25
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/alloc/src/boxed.rs:1866:9
  38:     0x7fb5eea5bc13 - std::sys::unix::thread::Thread::new::thread_start::h9051d9bccbad51db
                               at /rustc/27af5175497936ea3413bef5816e7c0172514b9c/library/std/src/sys/unix/thread.rs:108:17
  39:     0x7fb5ee71fb1a - start_thread
  40:     0x7fb5ee7a4660 - __GI___clone3
  41:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (27af51754 2022-04-20) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental -Z miri-track-pointer-tag=1

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```
</details>
