### ISSUE TITLE
Panic when multiple alloc-id's to track specified

### ISSUE THREAD

**Issue by fprasx** [rust-lang/miri#2110]
Hi,

Running miri as `MIRIFLAGS="-Zmiri-track-alloc-id=2001,11218" cargo miri run` produces the following issue:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `/Users/littlegoombas/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo-miri target/miri/x86_64-apple-darwin/debug/unlocked`
thread 'main' panicked at '-Zmiri-track-alloc-id requires a valid non-zero `u64` argument', src/tools/miri/src/bin/miri.rs:438:29
stack backtrace:
   0:        0x10d3144f1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h55afb1013a03bec9
   1:        0x10d37433b - core::fmt::write::hf346347c8bd39f92
   2:        0x10d3056ee - std::io::Write::write_fmt::h3ee7a608c2b4575b
   3:        0x10d318860 - std::panicking::default_hook::{{closure}}::hd379186b8ed80e63
   4:        0x10d318544 - std::panicking::default_hook::hb6f0fa309b9519b8
   5:        0x11934d3ea - rustc_driver[5ffba989829933c0]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x10d31912c - std::panicking::rust_panic_with_hook::h5485f9739aa6a2f1
   7:        0x10c8ce0db - std[41cdabac24a36933]::panicking::begin_panic::<&str>::{closure#0}
   8:        0x10c8ce0a7 - std[41cdabac24a36933]::sys_common::backtrace::__rust_end_short_backtrace::<std[41cdabac24a36933]::panicking::begin_panic<&str>::{closure#0}, !>
   9:        0x10ca804ce - std[41cdabac24a36933]::panicking::begin_panic::<&str>
  10:        0x10c8cc0fa - miri[4b72d49b4fbf7349]::main
  11:        0x10c8ce086 - std[41cdabac24a36933]::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>
  12:        0x10c8d261c - std[41cdabac24a36933]::rt::lang_start::<()>::{closure#0}
  13:        0x10d313b15 - std::rt::lang_start_internal::hca191b59d552af3d
  14:        0x10c8cd119 - _main

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.61.0-nightly (68369a041 2022-02-22) running on x86_64-apple-darwin

note: compiler flags: --crate-type bin -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental -Z miri-track-alloc-id=2001,11218

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
``` 
I looked at [`src/bin/miri.rs:438:29`](https://github.com/rust-lang/miri/blob/master/src/bin/miri.rs#L438) and it looks like that part of the code is for `-Zmiri-track-call-id`, so I'm a little confused. I also looked at `parse_comma_list` and the `-Zmiri-track-call-id` code and I don't see anywhere it would panic like this.

**Comment by oli-obk** [comment]
Your miri is from February. Try updating your nightly version with rustup. Miri is distributed with nightly, so you don't automatically get new versions unless you update nightly

**Comment by RalfJung** [comment]
I'll close this then; please comment if updating Miri does not fix this. :)
