### ISSUE TITLE
ice: failed to find required Rust item: ["core", "ascii", "escape_default"]

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/miri#2120]
code:
````rust
// build-fail

#![feature(lang_items, no_core)]
#![no_core]

#[lang="copy"] pub trait Copy { }
#[lang="sized"] pub trait Sized { }

// error-pattern:requires `start` lang_item

fn main() {}
````

stracktrace:
````
WARNING: Ignoring `RUSTC_WRAPPER` environment variable, Miri does not support wrapping.
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `/home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri target/miri/x86_64-unknown-linux-gnu/debug/miri`
thread 'rustc' panicked at 'failed to find required Rust item: ["core", "ascii", "escape_default"]', src/tools/miri/src/helpers.rs:76:32
stack backtrace:
   0:     0x7f52a869de5d - std::backtrace_rs::backtrace::libunwind::trace::h7a9c384780f2ae7b
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f52a869de5d - std::backtrace_rs::backtrace::trace_unsynchronized::heb75d166ca8b8236
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f52a869de5d - std::sys_common::backtrace::_print_fmt::h322cd7edf00cb3b5
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f52a869de5d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2bdd168863171e89
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f52a86f9adc - core::fmt::write::he97f80a3d639b1e1
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/core/src/fmt/mod.rs:1196:17
   5:     0x7f52a868f5e1 - std::io::Write::write_fmt::hfad334cf5c2887e6
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/io/mod.rs:1654:15
   6:     0x7f52a86a0b75 - std::sys_common::backtrace::_print::hb3fd4d16502c8b4b
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f52a86a0b75 - std::sys_common::backtrace::print::h20c8699087b98c21
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f52a86a0b75 - std::panicking::default_hook::{{closure}}::hceced8f030c627d7
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/panicking.rs:295:22
   9:     0x7f52a86a07e9 - std::panicking::default_hook::hf622cc58f7fb1da8
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/panicking.rs:314:9
  10:     0x7f52a8ee84a1 - rustc_driver[8eec3efc1f3aef49]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f52a86a1346 - std::panicking::rust_panic_with_hook::h6a32c5574ceba44d
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/panicking.rs:702:17
  12:     0x7f52a86a1147 - std::panicking::begin_panic_handler::{{closure}}::h33a7eb85cc49019a
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/panicking.rs:588:13
  13:     0x7f52a869e314 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc4249165d4ceafc
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f52a86a0e79 - rust_begin_unwind
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/panicking.rs:584:5
  15:     0x7f52a8666133 - core::panicking::panic_fmt::hea2f72507c137b32
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/core/src/panicking.rs:142:14
  16:     0x55cda92f8c94 - miri[d5b480a36bf1dfae]::eval::create_ecx
  17:     0x55cda92f99f3 - miri[d5b480a36bf1dfae]::eval::eval_entry
  18:     0x55cda92656ab - <rustc_interface[d03aac2056e219e8]::passes::QueryContext>::enter::<<miri[3f1dfd7966231fd0]::MiriCompilerCalls as rustc_driver[8eec3efc1f3aef49]::Callbacks>::after_analysis::{closure#0}, ()>
  19:     0x55cda9268e2e - <miri[3f1dfd7966231fd0]::MiriCompilerCalls as rustc_driver[8eec3efc1f3aef49]::Callbacks>::after_analysis
  20:     0x7f52aaf58a85 - <rustc_interface[d03aac2056e219e8]::interface::Compiler>::enter::<rustc_driver[8eec3efc1f3aef49]::run_compiler::{closure#1}::{closure#2}, core[c5a39be06b715266]::result::Result<core[c5a39be06b715266]::option::Option<rustc_interface[d03aac2056e219e8]::queries::Linker>, rustc_errors[ddf493a40e6cbb28]::ErrorGuaranteed>>
  21:     0x7f52aaf80e1f - rustc_span[5dae44024ba07c23]::with_source_map::<core[c5a39be06b715266]::result::Result<(), rustc_errors[ddf493a40e6cbb28]::ErrorGuaranteed>, rustc_interface[d03aac2056e219e8]::interface::create_compiler_and_run<core[c5a39be06b715266]::result::Result<(), rustc_errors[ddf493a40e6cbb28]::ErrorGuaranteed>, rustc_driver[8eec3efc1f3aef49]::run_compiler::{closure#1}>::{closure#1}>
  22:     0x7f52aaf6c9a4 - rustc_interface[d03aac2056e219e8]::interface::create_compiler_and_run::<core[c5a39be06b715266]::result::Result<(), rustc_errors[ddf493a40e6cbb28]::ErrorGuaranteed>, rustc_driver[8eec3efc1f3aef49]::run_compiler::{closure#1}>
  23:     0x7f52aaf56f82 - <scoped_tls[9a81942410e5ea2f]::ScopedKey<rustc_span[5dae44024ba07c23]::SessionGlobals>>::set::<rustc_interface[d03aac2056e219e8]::interface::run_compiler<core[c5a39be06b715266]::result::Result<(), rustc_errors[ddf493a40e6cbb28]::ErrorGuaranteed>, rustc_driver[8eec3efc1f3aef49]::run_compiler::{closure#1}>::{closure#0}, core[c5a39be06b715266]::result::Result<(), rustc_errors[ddf493a40e6cbb28]::ErrorGuaranteed>>
  24:     0x7f52aaf6e09f - std[87b888c30fb8b53d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[d03aac2056e219e8]::util::run_in_thread_pool_with_globals<rustc_interface[d03aac2056e219e8]::interface::run_compiler<core[c5a39be06b715266]::result::Result<(), rustc_errors[ddf493a40e6cbb28]::ErrorGuaranteed>, rustc_driver[8eec3efc1f3aef49]::run_compiler::{closure#1}>::{closure#0}, core[c5a39be06b715266]::result::Result<(), rustc_errors[ddf493a40e6cbb28]::ErrorGuaranteed>>::{closure#0}, core[c5a39be06b715266]::result::Result<(), rustc_errors[ddf493a40e6cbb28]::ErrorGuaranteed>>
  25:     0x7f52aaf6e1d9 - <<std[87b888c30fb8b53d]::thread::Builder>::spawn_unchecked_<rustc_interface[d03aac2056e219e8]::util::run_in_thread_pool_with_globals<rustc_interface[d03aac2056e219e8]::interface::run_compiler<core[c5a39be06b715266]::result::Result<(), rustc_errors[ddf493a40e6cbb28]::ErrorGuaranteed>, rustc_driver[8eec3efc1f3aef49]::run_compiler::{closure#1}>::{closure#0}, core[c5a39be06b715266]::result::Result<(), rustc_errors[ddf493a40e6cbb28]::ErrorGuaranteed>>::{closure#0}, core[c5a39be06b715266]::result::Result<(), rustc_errors[ddf493a40e6cbb28]::ErrorGuaranteed>>::{closure#1} as core[c5a39be06b715266]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  26:     0x7f52a86ab253 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h23107667314c5666
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/alloc/src/boxed.rs:1872:9
  27:     0x7f52a86ab253 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8a72a46bb071903a
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/alloc/src/boxed.rs:1872:9
  28:     0x7f52a86ab253 - std::sys::unix::thread::Thread::new::thread_start::h81657d69ed68fad8
                               at /rustc/6dd68402c5d7da168f87d8551dd9aed1d8a21893/library/std/src/sys/unix/thread.rs:108:17
  29:     0x7f52a839b5c2 - start_thread
  30:     0x7f52a8420584 - __clone
  31:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (6dd68402c 2022-05-11) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental -C target-cpu=native

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

````

**Comment by matthiaskrgr** [comment]
````rust

    /// Gets an instance for a path.
    fn resolve_path(&self, path: &[&str]) -> ty::Instance<'tcx> {
        let did = try_resolve_did(self.eval_context_ref().tcx.tcx, path)
            .unwrap_or_else(|| panic!("failed to find required Rust item: {:?}", path));
        ty::Instance::mono(self.eval_context_ref().tcx.tcx, did)
    }
    
````

would it make sense to exit a bit more gracefully in case of `no_core` ?

**Comment by oli-obk** [comment]
Considering that rustc also ICEs a lot with no_core, I think we're not going to address this.

There are so many corner cases, we'd need some holistic way (instead of patching individual ICEs) to handle no_core better before doing anything in miri

**Comment by RalfJung** [comment]
If you want to replace `panic` by `tcx.sess.fatal`, I would not object, but indeed I think that's about as far as it makes sense to go.
