### ISSUE TITLE
Miri ICEs in crossbeam

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2389]
The following code [causes an ICE](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c9d57154635126cebe07fdcef310348f):
```rust
fn main() {
    crossbeam::epoch::pin();
}
```
backtrace:
```
thread 'rustc' panicked at 'slice index starts at 17 but ends at 0', library/core/src/slice/index.rs:92:5
stack backtrace:
   0:     0x7f2a1122fed0 - std::backtrace_rs::backtrace::libunwind::trace::h6b3f9f41ee650c4f
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f2a1122fed0 - std::backtrace_rs::backtrace::trace_unsynchronized::he56cb04310aea81a
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2a1122fed0 - std::sys_common::backtrace::_print_fmt::h6d4ec34d6cd34171
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f2a1122fed0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h01911f0526d8b05c
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f2a1128b2ac - core::fmt::write::h49f323f7091ea1c8
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/fmt/mod.rs:1198:17
   5:     0x7f2a11220d85 - std::io::Write::write_fmt::hbf1f476d48d43edd
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/io/mod.rs:1672:15
   6:     0x7f2a11232ba1 - std::sys_common::backtrace::_print::h2bbdb393c4180f57
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f2a11232ba1 - std::sys_common::backtrace::print::h4200c2a0dbbbc055
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f2a11232ba1 - std::panicking::default_hook::{{closure}}::h393b25bd4d38364f
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:295:22
   9:     0x7f2a11232873 - std::panicking::default_hook::h70f1f206e4c542c6
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:314:9
  10:     0x7f2a13a8a5f1 - <rustc_driver[72308b4096139644]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[cd150e9e29982b29]::ops::function::FnOnce<(&core[cd150e9e29982b29]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f2a112333d6 - std::panicking::rust_panic_with_hook::hdfebab2861adaf27
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:702:17
  12:     0x7f2a11233227 - std::panicking::begin_panic_handler::{{closure}}::h7b45e1150590a6fe
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:588:13
  13:     0x7f2a112303b4 - std::sys_common::backtrace::__rust_end_short_backtrace::hcfb5f80ba126c43c
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f2a11232f52 - rust_begin_unwind
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:584:5
  15:     0x7f2a11287d83 - core::panicking::panic_fmt::h819a1bea3462d6ca
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/panicking.rs:142:14
  16:     0x7f2a1128e6f6 - core::slice::index::slice_index_order_fail_rt::hfc503f89c32b6542
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/slice/index.rs:92:5
  17:     0x7f2a1127f3c7 - core::ops::function::FnOnce::call_once::h3e66dd9ef257e867
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/ops/function.rs:248:5
  18:     0x7f2a11286436 - core::intrinsics::const_eval_select::h3984c891c53c21c1
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/intrinsics.rs:2701:5
  19:     0x7f2a1128e676 - core::slice::index::slice_index_order_fail::h98cf8d46d0f9ab2b
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/slice/index.rs:87:14
  20:     0x5644f2300b0f - <miri[54aa37d0a5b4e47b]::stacked_borrows::stack::Stack>::access
  21:     0x5644f2301161 - <miri[54aa37d0a5b4e47b]::stacked_borrows::stack::Stack>::grant
  22:     0x5644f2277eb2 - <rustc_const_eval[b1c97f8df3032a21]::interpret::eval_context::InterpCx<miri[54aa37d0a5b4e47b]::machine::Evaluator> as miri[54aa37d0a5b4e47b]::helpers::EvalContextExt>::visit_freeze_sensitive::<<rustc_const_eval[b1c97f8df3032a21]::interpret::eval_context::InterpCx<miri[54aa37d0a5b4e47b]::machine::Evaluator> as miri[54aa37d0a5b4e47b]::stacked_borrows::EvalContextPrivExt>::reborrow::{closure#1}>
  23:     0x5644f22c75a7 - <rustc_const_eval[b1c97f8df3032a21]::interpret::eval_context::InterpCx<miri[54aa37d0a5b4e47b]::machine::Evaluator> as miri[54aa37d0a5b4e47b]::stacked_borrows::EvalContextPrivExt>::retag_reference
  24:     0x5644f2254571 - <rustc_const_eval[b1c97f8df3032a21]::interpret::eval_context::InterpCx<miri[54aa37d0a5b4e47b]::machine::Evaluator>>::statement
  25:     0x5644f22fdf04 - miri[54aa37d0a5b4e47b]::eval::eval_entry
```
So, somewhere inside Stacked Borrows. Sadly this misses many line numbers. Would be good to get a self-contained testcase that does not need crossbeam.

Cc @saethlin who touches this code recently (but then so did I)

**Comment by RalfJung** [comment]
<details><summary>Better backtrace</summary>

```
thread 'rustc' panicked at 'slice index starts at 17 but ends at 0', library/core/src/slice/index.rs:92:5
stack backtrace:
   0:     0x7fe23aca37e0 - std::backtrace_rs::backtrace::libunwind::trace::h69a776dda5da45f0
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7fe23aca37e0 - std::backtrace_rs::backtrace::trace_unsynchronized::hc3b34bbe4f05c98d
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe23aca37e0 - std::sys_common::backtrace::_print_fmt::hf27749ba2c2f9a1f
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fe23aca37e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he4feca78ac845112
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fe23acfd8dc - core::fmt::write::h860d5859bc68e731
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/core/src/fmt/mod.rs:1198:17
   5:     0x7fe23ac94b45 - std::io::Write::write_fmt::h895cab2ccd1849dd
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/std/src/io/mod.rs:1672:15
   6:     0x7fe23aca64b1 - std::sys_common::backtrace::_print::h36a8914d2bf6aae2
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fe23aca64b1 - std::sys_common::backtrace::print::h37d10cfc6e5aee82
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fe23aca64b1 - std::panicking::default_hook::{{closure}}::hf43c273c32290ed0
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/std/src/panicking.rs:295:22
   9:     0x7fe23aca6183 - std::panicking::default_hook::hdbbcdb9c288fa2dc
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/std/src/panicking.rs:314:9
  10:     0x7fe23b550954 - rustc_driver[fccbb1957a724785]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fe23aca6c86 - std::panicking::rust_panic_with_hook::h0aa248201c01714c
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/std/src/panicking.rs:702:17
  12:     0x7fe23aca6ad7 - std::panicking::begin_panic_handler::{{closure}}::h660afaa68ea6fcaf
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/std/src/panicking.rs:588:13
  13:     0x7fe23aca3cc4 - std::sys_common::backtrace::__rust_end_short_backtrace::hb7dbd2e3304b729d
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fe23aca6802 - rust_begin_unwind
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/std/src/panicking.rs:584:5
  15:     0x7fe23ac69f43 - core::panicking::panic_fmt::h628c5fb2fb3ed665
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/core/src/panicking.rs:142:14
  16:     0x7fe23ad00cf6 - core::slice::index::slice_index_order_fail_rt::hf441de27d6de247e
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/core/src/slice/index.rs:92:5
  17:     0x7fe23acf1cf7 - core::ops::function::FnOnce::call_once::h7c17fa81932ba0a4
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/core/src/ops/function.rs:248:5
  18:     0x7fe23acf8d56 - core::intrinsics::const_eval_select::h45d3a83e95fad083
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/core/src/intrinsics.rs:2701:5
  19:     0x7fe23ac6a0c6 - core::slice::index::slice_index_order_fail::h9e8ed1b11aa383e8
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/core/src/slice/index.rs:87:14
  20:     0x55c8a6f9f484 - <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index_mut::hf6d30a8c571a3219
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/core/src/slice/index.rs:313:13
  21:     0x55c8a6f9f484 - core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut::h9be312bfb4252269
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/alloc/src/vec/mod.rs:2639:9
  22:     0x55c8a6f9f484 - <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut::hb1bd3f0540d013da
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/library/alloc/src/vec/mod.rs:2639:9
  23:     0x55c8a6f9f484 - miri::stacked_borrows::stack::Stack::disable_uniques_starting_at::hc4001ffa48447c11
                               at /home/r/src/rust/miri/src/stacked_borrows/stack.rs:302:30
  24:     0x55c8a705e12e - miri::stacked_borrows::<impl miri::stacked_borrows::stack::Stack>::access::h982eb9dece078ee2
                               at /home/r/src/rust/miri/src/stacked_borrows/mod.rs:471:13
  25:     0x55c8a705e8ed - miri::stacked_borrows::<impl miri::stacked_borrows::stack::Stack>::grant::hdafe79283680ef10
                               at /home/r/src/rust/miri/src/stacked_borrows/mod.rs:597:13
  26:     0x55c8a6fe9ce1 - miri::stacked_borrows::EvalContextPrivExt::reborrow::{{closure}}::{{closure}}::h8a5f18291e0d40a5
                               at /home/r/src/rust/miri/src/stacked_borrows/mod.rs:926:25
  27:     0x55c8a6fe9ce1 - miri::stacked_borrows::Stacks::for_each::h6c1656f761d25832
                               at /home/r/src/rust/miri/src/stacked_borrows/mod.rs:649:13
  28:     0x55c8a6fe9ce1 - miri::stacked_borrows::EvalContextPrivExt::reborrow::{{closure}}::h934f8c158cd8362f
                               at /home/r/src/rust/miri/src/stacked_borrows/mod.rs:925:21
  29:     0x55c8a6fe9ce1 - miri::helpers::EvalContextExt::visit_freeze_sensitive::{{closure}}::h98b4c145cda5fdac
                               at /home/r/src/rust/miri/src/helpers.rs:316:17
  30:     0x55c8a6fe9ce1 - miri::helpers::EvalContextExt::visit_freeze_sensitive::h635e5bda18227d8c
                               at /home/r/src/rust/miri/src/helpers.rs:354:9
  31:     0x55c8a7032753 - miri::stacked_borrows::EvalContextPrivExt::reborrow::h10a177a7c1906f09
                               at /home/r/src/rust/miri/src/stacked_borrows/mod.rs:906:17
  32:     0x55c8a7032753 - miri::stacked_borrows::EvalContextPrivExt::retag_reference::h3be221adfab68ecf
                               at /home/r/src/rust/miri/src/stacked_borrows/mod.rs:995:24
  33:     0x55c8a6f68b63 - miri::stacked_borrows::EvalContextExt::retag::RetagVisitor::retag_place::h86cfbba7c821bd6f
                               at /home/r/src/rust/miri/src/stacked_borrows/mod.rs:1065:27
  34:     0x55c8a6f68b63 - <miri::stacked_borrows::EvalContextExt::retag::RetagVisitor as rustc_const_eval::interpret::visitor::MutValueVisitor<miri::machine::Evaluator>>::visit_value::h890f8212aa0ae66b
                               at /home/r/src/rust/miri/src/stacked_borrows/mod.rs:1092:21
  35:     0x55c8a6fcac46 - miri::stacked_borrows::EvalContextExt::retag::hc0d74dcb3324a2a3
                               at /home/r/src/rust/miri/src/stacked_borrows/mod.rs:1026:16
  36:     0x55c8a6fcac46 - <miri::machine::Evaluator as rustc_const_eval::interpret::machine::Machine>::retag::hc5f1ec900719dd96
                               at /home/r/src/rust/miri/src/machine.rs:869:52
  37:     0x55c8a6fcac46 - rustc_const_eval::interpret::step::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::statement::hf380e1301902836d
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/compiler/rustc_const_eval/src/interpret/step.rs:114:17
  38:     0x55c8a6f665c4 - rustc_const_eval::interpret::step::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::step::h2a7dcf73d9aef02d
                               at /rustc/4603ac31b0655793a82f110f544dc1c6abc57bb7/compiler/rustc_const_eval/src/interpret/step.rs:60:13
  39:     0x55c8a6f665c4 - miri::eval::eval_entry::{{closure}}::h1475a24cb60c3097
                               at /home/r/src/rust/miri/src/eval.rs:341:29
  40:     0x55c8a6f665c4 - miri::eval::eval_entry::hfc2bef5af01361c7
                               at /home/r/src/rust/miri/src/eval.rs:335:38
```

</details>

This points here:
https://github.com/rust-lang/miri/blob/5d5999ab13e849c66f39b23a685512110e0d8eee/src/stacked_borrows/stack.rs#L302
so yeah looks like some trouble with the cache?

**Comment by RalfJung** [comment]
The panic message does not change with cache integrity checks.

Here's an interpreter backtrace of where in the code Miri is when this happens:
```
note: the place in the program where the ICE was triggered
   --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.9/src/internal.rs:423:44
    |
423 |         self.collector.with(|c| unsafe { &**c })
    |                                            ^^
    |
    = note: inside closure at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.9/src/internal.rs:423:44
    = note: inside `crossbeam::crossbeam_epoch::primitive::cell::UnsafeCell::<std::mem::ManuallyDrop<crossbeam::crossbeam_epoch::Collector>>::with::<&crossbeam::crossbeam_epoch::Collector, [closure@crossbeam::crossbeam_epoch::internal::Local::collector::{closure#0}]>` at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.9/src/lib.rs:116:17
    = note: inside `crossbeam::crossbeam_epoch::internal::Local::collector` at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.9/src/internal.rs:423:9
    = note: inside `crossbeam::crossbeam_epoch::internal::Local::global` at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.9/src/internal.rs:417:10
    = note: inside `crossbeam::crossbeam_epoch::internal::Local::pin` at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.9/src/internal.rs:509:17
    = note: inside `crossbeam::crossbeam_epoch::LocalHandle::pin` at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.9/src/collector.rs:81:18
    = note: inside closure at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.9/src/default.rs:32:26
    = note: inside closure at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.9/src/default.rs:52:23
    = note: inside `std::thread::LocalKey::<crossbeam::crossbeam_epoch::LocalHandle>::try_with::<[closure@crossbeam::crossbeam_epoch::default::with_handle<[closure@crossbeam::crossbeam_epoch::pin::{closure#0}], crossbeam::crossbeam_epoch::Guard>::{closure#0}], crossbeam::crossbeam_epoch::Guard>` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/thread/local.rs:445:16
    = note: inside `crossbeam::crossbeam_epoch::default::with_handle::<[closure@crossbeam::crossbeam_epoch::pin::{closure#0}], crossbeam::crossbeam_epoch::Guard>` at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.9/src/default.rs:51:5
    = note: inside `crossbeam::crossbeam_epoch::pin` at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.9/src/default.rs:32:5
note: inside `main` at src/main.rs:7:5
   --> src/main.rs:7:5
    |
7   |     crossbeam::epoch::pin();
    |     ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by saethlin** [comment]
I didn't think to be searching for ICEs in all my Miri logs, I think I have about 506 reproducers for this. _sigh_

I think the problem is that the cache integrity check only asserts that all `Unique` items are in the range, not that the range doesn't extend beyond the `Unique`s in the stack.

**Comment by RalfJung** [comment]
> I think I have about 506 reproducers for this. sigh

:joy: well I hope one of them will make for a good testcase. ;)

> I think the problem is that the cache integrity check only asserts that all Unique items are in the range, not that the range doesn't extend beyond the Uniques in the stack.

... or indeed beyond the size of the stack. If it was just unnecessarily bug but still in-bounds, that would be fine.

**Comment by RalfJung** [comment]
@taiki-e the latest nightly has a Miri where the ICE should be fixed. :)

**Comment by taiki-e** [comment]
Thanks!
