### ISSUE TITLE
`cargo miri setup` no longer works for locally installed toolchains

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/miri#3160]
I have a locally installed toolchain that I installed m into RUSTUP_HOME via `x.py install`.

When I now run `cargo +mytoolchain miri setup`, this no longer works:

````
at 18:15:47 ❯ RUST_BACKTRACE=1 ~/.cargo/bin/cargo +local-debug-assertions miri setup
Preparing a sysroot for Miri (target: x86_64-unknown-linux-gnu)...
thread 'main' panicked at src/cargo/util/rustc.rs:86:13:
commit hash must be a hex string
stack backtrace:
   0: rust_begin_unwind
             at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:72:14
   2: <cargo::util::rustc::Rustc>::new::{closure#2}
   3: <core::option::Option<&str>>::map::<alloc::string::String, <cargo::util::rustc::Rustc>::new::{closure#2}>
             at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/option.rs:1072:29
   4: <cargo::util::rustc::Rustc>::new
             at /home/matthias/vcs/github/rust_debug_assertions/src/tools/cargo/src/cargo/util/rustc.rs:85:57
   5: <cargo::util::config::Config>::load_global_rustc
             at /home/matthias/vcs/github/rust_debug_assertions/src/tools/cargo/src/cargo/util/config/mod.rs:414:9
   6: <cargo::core::compiler::build_context::target_info::RustcTargetData>::new
             at /home/matthias/vcs/github/rust_debug_assertions/src/tools/cargo/src/cargo/core/compiler/build_context/target_info.rs:885:21
   7: cargo::ops::cargo_compile::create_bcx
             at /home/matthias/vcs/github/rust_debug_assertions/src/tools/cargo/src/cargo/ops/cargo_compile/mod.rs:240:27
   8: cargo::ops::cargo_compile::compile_ws
             at /home/matthias/vcs/github/rust_debug_assertions/src/tools/cargo/src/cargo/ops/cargo_compile/mod.rs:151:15
   9: cargo::ops::cargo_compile::compile_with_exec
             at /home/matthias/vcs/github/rust_debug_assertions/src/tools/cargo/src/cargo/ops/cargo_compile/mod.rs:141:5
  10: cargo::ops::cargo_compile::compile
             at /home/matthias/vcs/github/rust_debug_assertions/src/tools/cargo/src/cargo/ops/cargo_compile/mod.rs:128:5
  11: cargo::commands::check::exec
             at /home/matthias/vcs/github/rust_debug_assertions/src/tools/cargo/src/bin/cargo/commands/check.rs:56:5
  12: cargo::cli::main
             at /home/matthias/vcs/github/rust_debug_assertions/src/tools/cargo/src/bin/cargo/cli.rs:184:5
  13: cargo::main
             at /home/matthias/vcs/github/rust_debug_assertions/src/tools/cargo/src/bin/cargo/main.rs:31:9
  14: <fn() as core::ops::function::FnOnce<()>>::call_once
             at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal error: failed to build sysroot: sysroot build failed
````

**Comment by matthiaskrgr** [comment]
wondering if its related to https://github.com/rust-lang/rust/pull/117797

**Comment by RalfJung** [comment]
The panic originates [here](https://github.com/rust-lang/cargo/blob/f4a1a0373a5ace5ff50b9a1fa404cf45608d3d29/src/cargo/util/rustc.rs#L86-L89) it seems. Unfortunately the panic message doesn't way what it got instead of a hex string.

> installed m into RUSTUP_HOME via x.py install.

FWIW I don't know if this ever worked. I usually use a toolchain that's linked to my `rustc/build/host` directory.

**Comment by RalfJung** [comment]
This looks like a cargo or rustc bug to me, Miri doesn't change the output of `commit-hash`... but it's hard to say. Miri does intercept `rustc` but when that goes wrong, I'd expect the output to not contain `commit-hash:` at all any more, and given the codepath this is on, it seems the output was present, it just did not have the expected format.

https://github.com/rust-lang/cargo/pull/12963 should make this easier to debug at least.

**Comment by RalfJung** [comment]
When I ask that locally built rustc for its commit-hash, I get `unknown`:
```
$ rustc +rustc-s1 -vV
rustc 1.76.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.76.0-dev
LLVM version: 17.0.4
```
So that would explain why cargo panics. Cc @weihanglo @ehuss (from https://github.com/rust-lang/cargo/pull/12625)

What I don't understand is why this does not fail in `./x.py test miri`. Maybe that is still using the bootstrap cargo?

**Comment by RalfJung** [comment]
Maybe cargo should recognize `unknown` and treat it as `None` (not having a commit-hash already seems to be an option, just having an invalid one is bad).

**Comment by ehuss** [comment]
Sorry, I forgot about that situation. @weihanglo, can you follow up on this?

**Comment by weihanglo** [comment]
Just posted a PR: https://github.com/rust-lang/cargo/pull/12965

Let me know if it doesn't work.

**Comment by RalfJung** [comment]
Fixed by https://github.com/rust-lang/cargo/pull/12965. Thanks!
